// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.1
// - protoc             v3.21.12
// source: tty/api.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTtyTtyVersion = "/tty.Tty/TtyVersion"

type TtyHTTPServer interface {
	// TtyVersion 增加玩家购买的礼包次数
	TtyVersion(context.Context, *Empty) (*TtyVersionResp, error)
}

func RegisterTtyHTTPServer(s *http.Server, srv TtyHTTPServer) {
	r := s.Route("/")
	r.GET("tty/version", _Tty_TtyVersion0_HTTP_Handler(srv))
}

func _Tty_TtyVersion0_HTTP_Handler(srv TtyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTtyTtyVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TtyVersion(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TtyVersionResp)
		return ctx.Result(200, reply)
	}
}

type TtyHTTPClient interface {
	TtyVersion(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *TtyVersionResp, err error)
}

type TtyHTTPClientImpl struct {
	cc *http.Client
}

func NewTtyHTTPClient(client *http.Client) TtyHTTPClient {
	return &TtyHTTPClientImpl{client}
}

func (c *TtyHTTPClientImpl) TtyVersion(ctx context.Context, in *Empty, opts ...http.CallOption) (*TtyVersionResp, error) {
	var out TtyVersionResp
	pattern := "tty/version"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTtyTtyVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
